In [26]:
import pandas as pd
from sqlalchemy import create_engine

# Packet Loss

In [27]:
engine = create_engine("postgresql://postgres:postgres@postgres:5432/postgres") # postgresql://user:password@host:port/databasename
df = pd.read_sql_query("SELECT SUM(sent_packets) as sent, SUM(received_packets) as rcvd, country FROM ping_data GROUP BY country;", con=engine)

In [29]:
losses = []
losses_percent = []
for _, row in df.iterrows():
    ratio = 1 - (row['rcvd'] / row['sent'])
    losses.append(ratio)
    losses_percent.append(ratio * 100)
df.join(pd.DataFrame({'loss_ratio': losses, 'loss_percent': losses_percent}))

        sent      rcvd country  loss_ratio  loss_percent
0    1034184   1031883      AT    0.002225      0.222494
1    1458335   1447150      AU    0.007670      0.766971
2     465870    465213      BE    0.001410      0.141026
3     600501    573321      BR    0.045262      4.526221
4    4571922   4547207      CA    0.005406      0.540582
5    5416125   4401392      DE    0.187354     18.735406
6    2332480   2295240      ES    0.015966      1.596584
7    9480963   8320991      FR    0.122347     12.234749
8    4442860   4420661      GB    0.004997      0.499656
9     463038    461862      GR    0.002540      0.253975
10   1308654   1301314      HT    0.005609      0.560882
11   2566300   2509907      IT    0.021974      2.197444
12    496091    495421      NL    0.001351      0.135056
13   2110793   1542273      PH    0.269340     26.933953
14    454844    453899      PL    0.002078      0.207764
15    454466    452637      RE    0.004025      0.402450
16    541235    540327      SE    0.001678      0.167764
17  18789094  17180569      US    0.085610      8.560950
18   1001013    997781      VI    0.003229      0.322873